import type { Opening, OpeningCollection } from "../src/types.js";
import { openingBook } from "./getLatestEcoJson.js";

/**
 * From/To transition index structure.
 * Maps position-only FEN to arrays of full FENs representing transitions.
 */
export interface FromToIndex {
  /** Maps position → array of next position FENs */
  to: Record<string, string[]>;
  /** Maps position → array of previous position FENs */
  from: Record<string, string[]>;
}

// Cache for fromToIndex to avoid re-downloading
let fromToIndexCache: FromToIndex | null = null;

/**
 * Downloads and caches the pre-indexed from/to transition data from GitHub.
 * This file is generated by eco.json.tooling and maps position-only FENs to transition arrays.
 *
 * @returns Indexed transition data with to/from mappings
 *
 * @example
 * ```typescript
 * const index = await getFromToIndex();
 * const position = "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR";
 * const nextFens = index.to[position]; // FENs for e2-e4 position
 * ```
 */
export async function getFromToIndex(): Promise<FromToIndex> {
  if (fromToIndexCache) {
    return fromToIndexCache;
  }

  const url =
    "https://raw.githubusercontent.com/JeffML/eco.json/master/fromToPositionIndexed.json";

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch fromToPositionIndexed.json: ${response.status} ${response.statusText}`
    );
  }

  fromToIndexCache = await response.json();
  return fromToIndexCache!;
}

/**
 * Gets the next and previous opening positions for a given FEN.
 * Returns full Opening objects (not just FEN strings) by looking up transitions
 * in the pre-indexed data and enriching with opening book information.
 *
 * Uses position-only FEN for lookup to handle transpositions.
 *
 * @param fen - The FEN string to look up transitions for
 * @param openings - Optional pre-loaded opening collection (will fetch if not provided)
 * @returns Object with next and from Opening arrays
 *
 * @example
 * ```typescript
 * // Get transitions for e2-e4 position
 * const { next, from } = await getFromTos(
 *   "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"
 * );
 *
 * console.log(next[0].name); // "King's Pawn Opening: Sicilian Defense"
 * console.log(from[0].name); // "Starting Position"
 * ```
 */
export async function getFromTos(
  fen: string,
  openings?: OpeningCollection
): Promise<{
  next: Opening[];
  from: Opening[];
}> {
  // Load data if not provided
  const openingCollection = openings || (await openingBook());
  const fromToIndex = await getFromToIndex();

  // Extract position-only FEN (ignore turn, castling, en passant)
  const position = fen.split(" ")[0];

  // Get FEN arrays from index
  const nextFens = fromToIndex.to[position] || [];
  const fromFens = fromToIndex.from[position] || [];

  // Enrich with full Opening data
  const next = nextFens
    .map((f) => openingCollection[f])
    .filter((o): o is Opening => o != null);

  const from = fromFens
    .map((f) => openingCollection[f])
    .filter((o): o is Opening => o != null);

  return { next, from };
}

/**
 * Clears the cached fromToIndex, forcing a fresh download on next access.
 * Useful for testing or when data updates are expected.
 */
export function clearFromToCache(): void {
  fromToIndexCache = null;
}
